---
name: PR-pipeline
on:
    pull_request:
        branches:
            - master
jobs:
    validate_files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
            - run: |
                  pip install pre-commit
                  pre-commit install
                  pre-commit run --all-files
